
let pages=[];
const exampleSections=[{section_type:'hero',title:'Hero title',subtitle:'Subtitle',sort_order:1,is_visible:true,content:{kicker:'Meflay',button:{label:'Contact',url:'#contact'}}}];
async function loadPages(){await requireAuth(); const {data,error}=await db.from('pages').select('*').order('sort_order',{ascending:true}); if(error){toast(error.message);return} pages=data||[]; renderPages()}
function renderPages(){const body=$('#pagesTable'); body.innerHTML=pages.map(p=>`<tr><td>${p.sort_order}</td><td><strong>${escapeHtml(p.title)}</strong></td><td>${escapeHtml(p.slug)}</td><td><span class="status ${p.status}">${p.status}</span></td><td>${p.is_system?'Yes':'No'}</td><td><div class="row-actions"><button class="ghost-btn" onclick="editPage('${p.id}')">Edit</button></div></td></tr>`).join('')}
async function getSections(pageId){const {data}=await db.from('page_sections').select('*').eq('page_id',pageId).order('sort_order'); return data||[]}
function fillPage(p={},sections=exampleSections){$('#pageId').value=p.id||'';$('#pageTitle').value=p.title||'';$('#pageSlug').value=p.slug||'';$('#pageStatus').value=p.status||'draft';$('#pageOrder').value=p.sort_order||0;$('#pageSeoTitle').value=p.seo_title||'';$('#pageSeoDescription').value=p.seo_description||'';$('#pageSections').value=JSON.stringify(sections.map(s=>({section_type:s.section_type,title:s.title,subtitle:s.subtitle,sort_order:s.sort_order,is_visible:s.is_visible,content:s.content||{}})),null,2)}
window.editPage=async(id)=>{const p=pages.find(x=>x.id===id); fillPage(p,await getSections(id)); $('#pageModalTitle').textContent='Edit page'; openModal('#pageModal')}
$('#newPageBtn').addEventListener('click',()=>{fillPage({status:'draft'}); $('#pageModalTitle').textContent='New page'; openModal('#pageModal')})
$('#pageTitle').addEventListener('input',()=>{if(!$('#pageId').value) $('#pageSlug').value=slugify($('#pageTitle').value)})
$('#pageForm').addEventListener('submit',async e=>{e.preventDefault(); let sections; try{sections=JSON.parse($('#pageSections').value||'[]'); if(!Array.isArray(sections)) throw new Error('Sections must be an array')}catch(err){toast(err.message);return} const id=$('#pageId').value; const payload={title:$('#pageTitle').value.trim(),slug:$('#pageSlug').value.trim(),status:$('#pageStatus').value,sort_order:Number($('#pageOrder').value||0),seo_title:$('#pageSeoTitle').value.trim(),seo_description:$('#pageSeoDescription').value.trim()}; let result=id?await db.from('pages').update(payload).eq('id',id).select().single():await db.from('pages').insert(payload).select().single(); if(result.error){toast(result.error.message);return} const pageId=result.data.id; await db.from('page_sections').delete().eq('page_id',pageId); if(sections.length){const rows=sections.map((s,i)=>({page_id:pageId,section_type:s.section_type||'custom',title:s.title||'',subtitle:s.subtitle||'',sort_order:s.sort_order??i+1,is_visible:s.is_visible!==false,content:s.content||{}})); const {error}=await db.from('page_sections').insert(rows); if(error){toast(error.message);return}} closeModals(); toast('Page saved'); loadPages()})
loadPages();
